framework:
    validation:
        # Enables validator auto-mapping support.
        # For instance, basic validation constraints will be inferred from Repository's metadata.
        #auto_mapping:
        #    App\Model\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
