# Añadir item al carrito
add-item:
    path: /api/add_item
    controller: App\Infrastructure\Controller\AddItemController
    methods: POST

# Actualizar item al carrito
update-item:
    path: /api/update_item
    controller: App\Infrastructure\Controller\UpdateItemController
    methods: PUT

# borrar item al carrito
delete-item:
    path: /api/delete_item
    controller: App\Infrastructure\Controller\DeleteItemController
    methods: DELETE

# obtiene el numero total de items
get-total-items:
    path: /api/get_total_items
    controller: App\Infrastructure\Controller\GetTotalItemsController
    methods: GET

# lleva a la pasrela de compra del carrito
checkout:
    path: /api/checkout
    controller: App\Infrastructure\Controller\CheckoutController
    methods: POST
