# Añadir item al carrito
add-item:
    path: /api/add_item
    controller: App\Infrastructure\Controller\AddItemController
    methods: PUT

# Actualizar item al carrito
update-item:
    path: /api/update_item
    controller: App\Infrastructure\Controller\UpdateItemController
    methods: PUT
